---

- when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  name: Add fish repository for CentOS
  get_url:
    url: https://download.opensuse.org/repositories/shells:fish:release:2/CentOS_7/shells:fish:release:2.repo
    dest: /etc/yum.repos.d/
    mode: 0644
