---

- when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  name: Adding fish repository for CentOS
  get_url:
    url: https://download.opensuse.org/repositories/shells:fish:release:2/CentOS_7/shells:fish:release:2.repo
    dest: /etc/yum.repos.d/
    mode: 0644

- name: Installing fish shell
  package:
    name: fish
    state: present

- name: Checking oh-my-fish installation
  stat:
    path: '/etc/omf.installed'
  register: omf

- when: not omf.stat.exists
  block:  
    - name: Cloning oh-my-fish repo
      git:
        repo: 'https://github.com/oh-my-fish/oh-my-fish'
        dest: '/tmp/omf'
        clone: yes

    - name: Installing oh-my-fish
      become: true
      become_user: '{{ item.key }}'
      command: /tmp/omf/bin/install -y --offline --noninteractive
      with_dict: '{{ fullList }}'

    - name: Mark oh-my-fish installed with /etc/omf.installed
      file:
        path: /etc/omf.installed
        state: touch

    - name: Changing user shell
      user:
        name: '{{ item.key }}'
        shell: /usr/bin/fish
      with_dict: '{{ fullList }}'

- name: Creating fisk custom theme user directory
  file: 
    path: '{{ item.value }}/{{ item.key }}/.config/fish/functions'
    state: directory
    owner: '{{ item.key }}'
    group: '{{ item.key }}'
    recurse: yes
    mode: 0775
  with_dict: '{{ userlist }}'

- name: Creating fisk custom theme root directory
  file: 
    path: '{{ item.value }}/.config/fish/functions'
    state: directory
    recurse: yes
    mode: 0775
  with_dict: '{{ rootlist }}'

#- name: Creating fisk theme user directory
#  file: 
#    path: '{{ item.value }}/{{ item.key }}/.local/share/omf/themes/fisk'
#    state: directory
#    recurse: yes
#    mode: 0775
#  with_dict: '{{ userlist }}'

#- name: Creating fisk theme root directory
#  file: 
#    path: '{{ item.value }}/.local/share/omf/themes/fisk'
#    state: directory
#    recurse: yes
#    mode: 0775
#  with_dict: '{{ rootlist }}'

#- name: Installing fisk default theme user
#  template:
#    src: config.fisk.default.theme.j2
#    dest: '{{ item.value }}/{{ item.key }}/.local/share/omf/themes/fisk/fish_prompt.fish'
#    owner: '{{ item.key }}'
#    group: '{{ item.key }}'
#    mode: 0644
#  with_dict: '{{ userlist }}'

#- name: Installing fisk default theme root
#  template:
#    src: config.fisk.default.theme.j2
#    dest: '{{ item.value }}/.local/share/omf/themes/fisk/fish_prompt.fish'
#    owner: '{{ item.key }}'
#    group: '{{ item.key }}'
#    mode: 0644
#  with_dict: '{{ rootlist }}'

#- name: Installing fisk concat function user
#  template:
#    src: config.fisk.concat.function.j2
#    dest: '{{ item.value }}/{{ item.key }}/.local/share/omf/themes/fisk/_fisk_concat.fish'
#    owner: '{{ item.key }}'
#    group: '{{ item.key }}'
#    mode: 0644
#  with_dict: '{{ userlist }}'

#- name: Installing fisk concat function root
#  template:
#    src: config.fisk.concat.function.j2
#    dest: '{{ item.value }}/.local/share/omf/themes/fisk/_fisk_concat.fish'
#    owner: '{{ item.key }}'
#    group: '{{ item.key }}'
#    mode: 0644
#  with_dict: '{{ rootlist }}'

- name: Configuring fisk theme colours for user
  template:
    src: config.fisk.theme.colours.user.j2
    dest: '{{ item.value }}/{{ item.key }}/.config/fish/functions/fish_prompt.fish.NEW'
    owner: '{{ item.key }}'
    group: '{{ item.key }}'
    mode: 0777
  with_dict: '{{ userlist }}'

- name: Configuring fisk theme colours for root
  template:
    src: config.fisk.theme.colours.root.j2
    dest: '{{ item.value }}/.config/fish/functions/fish_prompt.fish.NEW'
    owner: '{{ item.key }}'
    group: '{{ item.key }}'
    mode: 0777
  with_dict: '{{ rootlist }}'

#- name: Symlinking user
#  file:
#    src: '{{ item.value }}{{ item.key }}/.local/share/omf/themes/fisk/fish_prompt.fish'
#    dest: '{{ item.value }}{{ item.key }}/.config/fish/functions/fish_prompt.fish'
#    state: link
#    force: yes
#  with_dict: '{{ userlist }}'

#- name: Symlinking root
#  file:
#    src: '{{ item.value }}/.local/share/omf/themes/fisk/fish_prompt.fish'
#    dest: '{{ item.value }}/.config/fish/functions/fish_prompt.fish'
#    state: link
#    force: yes
#  with_dict: '{{ rootlist }}'

...
