---

- when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  name: Adding fish repository for CentOS
  get_url:
    url: https://download.opensuse.org/repositories/shells:fish:release:2/CentOS_7/shells:fish:release:2.repo
    dest: /etc/yum.repos.d/
    mode: 0644

- name: Installing fish shell
  package:
    name: fish
    state: present

- name: Checking oh-my-fish installation
  stat:
    path: '/etc/omf.installed'
  register: omf

- when: not omf.stat.exists
  block:  
    - name: Cloning oh-my-fish repo
      git:
        repo: 'https://github.com/oh-my-fish/oh-my-fish'
        dest: '/tmp/omf'
        clone: yes

    - name: Installing oh-my-fish
      become: true
      become_user: '{{ item.key }}'
      command: /tmp/omf/bin/install -y --offline --noninteractive
      with_dict: '{{ fullList }}'

    - name: Mark oh-my-fish installed with /etc/omf.installed
      file:
        path: /etc/omf.installed
        state: touch

    - name: Changing user shell
      user:
        name: '{{ item.key }}'
        shell: /usr/bin/fish
      with_dict: '{{ fullList }}'

...
