---

- when: ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  name: Adding fish repository for CentOS
  get_url:
    url: https://download.opensuse.org/repositories/shells:fish:release:2/CentOS_7/shells:fish:release:2.repo
    dest: /etc/yum.repos.d/
    mode: 0644

- name: Installing fish shell
  package:
    name: fish
    state: present

#- name: Check if nerd fonts are installed
#  stat:
#    path: /usr/local/share/fonts/NerdFonts
#  register: fonts

#- name: Clone nerd fonts repo
#  git:
#    repo: 'https://github.com/ryanoasis/nerd-fonts'
#    dest: '/tmp/nerd-fonts'
#    clone: yes
#    depth: 1
#  when: not fonts.stat.exists

#- name: Install nerd fonts
#  become: true
#  command: /tmp/nerd-fonts/install.sh -S
#  when: not fonts.stat.exists

- name: Checking powerline font installation
  stat:
    path: /home/fred/.local/share/fonts
  register: fonts

- when: not fonts.stat.exists
  block:
    - name: Cloning powerline fonts repo
      git:
        repo: 'https://github.com/powerline/fonts.git'
        dest: '/tmp/powerline-fonts'
        clone: yes
        depth: 1

    - name: Installing powerline fonts
      become: true
      become_user: '{{ item.key }}'
      command: /tmp/powerline-fonts/install.sh -S
      with_dict: '{{ userlist }}'

- name: Checking oh-my-fish installation
  stat:
    path: '/etc/omf.installed'
  register: omf

- when: not omf.stat.exists
  block:  
    - name: Cloning oh-my-fish repo
      git:
        repo: 'https://github.com/oh-my-fish/oh-my-fish'
        dest: '/tmp/omf'
        clone: yes

    - name: Installing oh-my-fish
      become: true
      become_user: '{{ item.key }}'
      command: /tmp/omf/bin/install -y --offline --noninteractive
      with_dict: '{{ userlist }}'

    - name: Configuring fish theme
      template:
        src: config.fish.j2
        dest: '{{ item.value }}/{{ item.key }}/.config/fish/config.fish'
        owner: '{{ item.key }}'
        group: '{{ item.key }}'
        mode: 0644
      with_dict: '{{ userlist }}'

    - name: Ensuring diectory exists
      file: 
        path: '{{ item.value }}/{{ item.key }}/.config/fish/functions'
        state: directory
        recurse: yes
        mode: 0775
      with_dict: '{{ userlist }}'

    - name: Configuring fish colours
      template:
        src: config.fish.colours.j2
        dest: '{{ item.value }}/{{ item.key }}/.config/fish/functions/bobthefish_colors.fish'
        owner: '{{ item.key }}'
        group: '{{ item.key }}'
        mode: 0644
      with_dict: '{{ userlist }}'

    - name: Mark oh-my-fish installed with /etc/omf.installed
      file:
        path: /etc/omf.installed
        state: touch

    - name: Changing user shell
      user:
        name: '{{ item.key }}'
        shell: /usr/bin/fish
      with_dict: '{{ userlist }}'

...
