---
- name: Packer build Ansible
  hosts: localhost
  connection: local
  become: yes
  vars:
    userlist:
      fred: /home/
    fullList:
      #fred: /home/
      root: /root/

  roles:
    - utils
    #- sudoer
    - open-vm-tools
    - fish
    - update
    - plex
    - gnome-desktop
    #- test-feature
...