---
- hosts: localhost
  connection: local
  vars_prompt:
  - name: "rootpassword"
    prompt: "Enter your password to esxi"
    private: yes
  tasks:
  - vsphere_guest:
      vcenter_hostname: "192.168.1.1"
      esxi:
        datacenter: ha-datacenter
        hostname: "ESXi"
      username: "root"
      password: tst
      guest: newvm001
      state: powered_on
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
      vm_disk:
        disk1:
          size_gb: 10
          type: thin
          datastore: datastore1
          # VMs can be put into folders. The value given here is either the full path
          # to the folder (e.g. production/customerA/lamp) or just the last component
          # of the path (e.g. lamp):
          folder: 
      vm_nic:
        nic1:
          type: vmxnet3
          network: VM Network
          network_type: standard
      vm_hardware:
        memory_mb: 2048
        num_cpus: 2
        osid: Debian64Guest
        scsi: paravirtual
        vm_cdrom:
          type: "iso"
          iso_path: "datastore2/ISO/Debian-9.8.0-amd64-netinst.iso"
...
