---
- name: Basic Packages installation for CentOS
  yum:
    name:
      - sudo
      - curl
      - wget
      - gcc
      - net-tools
      - zsh
      - nano
      - nfs-utils
    state: latest
    update_cache: yes

- name: IUS repo installation
  yum:
    name:
      - https://centos7.iuscommunity.org/ius-release.rpm

- name: GIT package installation
  yum:
    name:
      - git2u-all
    
#- name: GIT install for CentOS
#  yum:
#    name:
#      - curl-devel
#      - expat-devel
#      - gettext-devel
#      - openssl-devel
#      - zlib-devel
#      - cpan
#    state: present
#    update_cache: yes

#- name: Get git binary
#  unarchive:
#    src: "{{ git_url }}"
#    dest: "{{ git_temp_dir }}"
#    remote_src: yes
#  changed_when: false

#- name: Make all git binary
#  make:
#    chdir: "{{ git_binary_dir }}"
#    target: all
#    params:
#      prefix: "{{ git_prefix }}"
#  changed_when: false

#- name: Make install git binary
#  make:
#    chdir: "{{ git_binary_dir }}"
#    target: install
#    params:
#      prefix: "{{ git_prefix }}"
#  changed_when: false

#- name: Remove file
#  file:
#    path: "{{ git_binary_dir }}"
#    state: absent
#  changed_when: false