---
- name: Basic Packages installation for Debian
  apt:
    name:
      - sudo
      - git
      - curl
      - wget
      - gcc
      - net-tools
      - zsh
      - nano
      - nfs-common
      - dirmngr
    state: latest
    update_cache: yes